name: Docker Image Python push to Dockerhub

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version (vX.X.X)
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Build the Docker image and push
       env:
         VERSION: ${{ github.event.inputs.version }}
         DOCKER_USER: ${{secrets.DOCKER_HUB_LOGIN}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PWD}}
         DOCKER_REGISTRY: ${{secrets.DOCKER_HUB_LOGIN}}/
       working-directory: ./embedding-calculator/
       run: |
         make build-images
         docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
         docker push ${DOCKER_REGISTRY}compreface-core
